apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-cicd
  namespace: my-api-cicd
  labels:
    app: my-api-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api-cicd
  template:
    metadata:
      labels:
        app: my-api-cicd
    spec:
      containers:
      - name: my-api-cicd
        image: moids77/my-api-cicd:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3