apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-api-cicd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: my-api-cicd
  managed-by: argocd