apiVersion: v1
kind: Service
metadata:
  name: my-api-cicd
  namespace: my-api-cicd
  labels:
    app: my-api-cicd
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: my-api-cicd